### ISSUE TITLE
Codici geografici "standard"

### ISSUE THREAD

**Issue by aborruso** [italia/covid19-opendata-vaccini#1]
Buonasera e grazie per il lavoro fatto.

In molti dei dataset ci sono colonne "geografiche":

- `area` per le regioni (la più diffusa);
- `provincia`
- `comune`

Potete aggiungere i rispettivi codici ISTAT in modo da poter valorizzare i dati, incrociandoli con altre fonti via JOIN?

E visto che c'è il corretto taglio a 21 regioni standard (le due province autonome), inserire la colonna con i codici NUTS2, che è la suddivisione territoriale standard e "giusta" per questi dati.

Grazie

**Comment by sabas** [comment]
https://www.istat.it/it/archivio/6789

**Comment by CapMar00** [comment]
Buongiorno,
mi unisco anch'io alla richiesta di avere i codici istat per le regioni, magari anche la data in formato YYYY-MM-DDTHH:MM:SS (ISO 8601) Ora italiana.
grazie

**Comment by alessiodl** [comment]
Appoggio la richiesta e mi unisco anche io

**Comment by MITEL-UNIUD** [comment]
Mi unisco anch'io alla richiesta.

**Comment by datateam-opendata** [comment]
Grazie @aborruso per questa issue. 
Il sistema di analisi dei dati è in fase di aggiornamento evolutivo. In questo momento si stanno valutando modifiche alla base dati e cercheremo di tener presente questa segnalazione per migliorare la fruibilità del dataset. Contestualmente verrà pubblicata in questo repository anche la roadmap di aggiornamento in modo da rendere trasparenti le scelte progettuali.

**Comment by aborruso** [comment]
@datateam-opendata segnalo un'azione strettamente correlata che verrà applicato allo schema dati dei dati del repo del Dipartimento della Protezione Civile: https://github.com/pcm-dpc/COVID-19/issues/1037#issue-785230408

> Saranno aggiunti anche i dati "codice_nuts_1", "codice_nuts_2" per il dataset regioni e "codice_nuts_1", "codice_nuts_2", "codice_nuts_3" per il dataset province per interoperare meglio con le informazioni geografiche

È un'ulteriore ragione forte per usare codici geografici "standard"

**Comment by aborruso** [comment]
@datateam-opendata e qui c'è un esempio del rischio di non usare codici standard, con un utente non italiano che non ha idea di cosa siano i codici geografici usati https://github.com/italia/covid19-opendata-vaccini/issues/33#issue-787214470

Usando anche le NUTS2 (e dichiarandolo) il problema sarebbe risolto

**Comment by datateam-opendata** [comment]
Grazie @aborruso per il prezioso suggerimento. Stiamo estendendo la roadmap di aggiornamento e cercheremo di tenere in considerazione le indicazioni date. Grazie ancora.

**Comment by aborruso** [comment]
> Grazie @aborruso per il prezioso suggerimento. Stiamo estendendo la roadmap di aggiornamento e cercheremo di tenere in considerazione le indicazioni date. Grazie ancora.

Grazie a voi. L'assenza di codici geografici standard è una lacuna forte, perché blocca l'interoperabilità diretta con altre fonti. Queste basi dati, visto il tema e l'importanza, non dovrebbero averle. 

A seguire i codici per mettere in correlazione le "vostre" etichette (`siglaRegione`), con i codici NUTS (`NUTS2`) e i codici regionali di ISTAT (`COD_REG`).

| NUTS2 | Name | siglaRegione | COD_REG |
| --- | --- | --- | --- |
| ITF1 | Abruzzo | ABR | 13 |
| ITF5 | Basilicata | BAS | 17 |
| ITF6 | Calabria | CAL | 18 |
| ITF3 | Campania | CAM | 15 |
| ITH5 | Emilia-Romagna | EMR | 08 |
| ITH4 | Friuli-Venezia Giulia | FVG | 06 |
| ITI4 | Lazio | LAZ | 12 |
| ITC3 | Liguria | LIG | 07 |
| ITC4 | Lombardia | LOM | 03 |
| ITI3 | Marche | MAR | 11 |
| ITF2 | Molise | MOL | 14 |
| ITC1 | Piemonte | PIE | 01 |
| ITH1 | Provincia Autonoma Bolzano / Bozen | PAB | 04 |
| ITH2 | Provincia Autonoma Trento | PAT | 04 |
| ITF4 | Puglia | PUG | 16 |
| ITG2 | Sardegna | SAR | 20 |
| ITG1 | Sicilia | SIC | 19 |
| ITI1 | Toscana | TOS | 09 |
| ITI2 | Umbria | UMB | 10 |
| ITC2 | Valle d'Aosta / Vallée d'Aoste | VDA | 02 |
| ITH3 | Veneto | VEN | 05 |

```
NUTS2,Name,siglaRegione,COD_REG
ITF1,Abruzzo,ABR,13
ITF5,Basilicata,BAS,17
ITF6,Calabria,CAL,18
ITF3,Campania,CAM,15
ITH5,Emilia-Romagna,EMR,08
ITH4,Friuli-Venezia Giulia,FVG,06
ITI4,Lazio,LAZ,12
ITC3,Liguria,LIG,07
ITC4,Lombardia,LOM,03
ITI3,Marche,MAR,11
ITF2,Molise,MOL,14
ITC1,Piemonte,PIE,01
ITH1,Provincia Autonoma Bolzano / Bozen,PAB,04
ITH2,Provincia Autonoma Trento,PAT,04
ITF4,Puglia,PUG,16
ITG2,Sardegna,SAR,20
ITG1,Sicilia,SIC,19
ITI1,Toscana,TOS,09
ITI2,Umbria,UMB,10
ITC2,Valle d'Aosta / Vallée d'Aoste,VDA,02
ITH3,Veneto,VEN,05
```

**Comment by aborruso** [comment]
E da oggi è veramente chiusa ;)

Grazie @datateam-opendata
