### ISSUE TITLE
Aggiungere numero di vaccinati (che hanno avuto 2 somministrazioni)

### ISSUE THREAD

**Issue by MITEL-UNIUD** [italia/covid19-opendata-vaccini#12]
Poiché sarà il dato più rilevante , suggerisco di aggiungere il numero di vaccinati, ovvero coloro che hanno avuto le due somministrazioni.

**Comment by carmelolg** [comment]
Volevo fare la stessa richiesta io. 
Per poter analizzare il trend è più utile sapere il dato della doppia somministrazione. Sarà possibile?

**Comment by LucaZeta** [comment]
Non tutti i vaccini richiedono la doppia somministrazione: sarebbe opportuno introdurre un nuovo contatore "nuovi vaccinati" come indicatore che, a seconda del vaccino trattato prenda in considerazione solo la prima o la seconda somministrazione. Qualcosa simile, per fare un parallelo, al campo nuovi_positivi che considerano solo i T0 positivi nel open dataset per l'incidenza.

In alternativa, più semplicemente, ma con un maggiore margine di approssimazione, si potrebbe aggiungere il "tipo vaccino" tra i campi che descrivono gli approvvigionamenti e le somministrazioni.

In finale, e lo ritengo rilevante, le informazioni così organizzate sono funzionali per un tracciamento logistico dei vaccini, mentre sono meno utili per un tracciamento che possa integrare le informazioni epidemiologiche.

**Comment by MITEL-UNIUD** [comment]
Certo, non tutti (anche se i primi 3 di cui disponiamo sì), infatti un campo "vaccinati" (o "nuovi vaccinati") cattura meglio di un dose1 dose2 l'informazione più importante.

**Comment by datateam-opendata** [comment]
Grazie @MITEL-UNIUD per la issue. Abbiamo provveduto ad inserire i campi relativi alla prima e seconda somministrazione. In questo momento i vaccini inoculati richiedono entrambi la dose di richiamo. Provvederemo ad estendere i campi nel futuro quando sarà necessario indicando il numero delle persone completamente vaccinate. Essendo risolta, chiudiamo la issue. Grazie ancora.
