### ISSUE TITLE
Dati vaccini sul sito della presidenza del Consiglio e aggiornamento repository

### ISSUE THREAD

**Issue by CapMar00** [italia/covid19-opendata-vaccini#121]
Buonasera,
l'ANSA annuncia che da domani i dati sui vaccini saranno consultabili sul sito della presidenza del Consiglio per Regione e categoria
https://www.ansa.it/sito/notizie/topnews/2021/03/25/vaccini-da-domani-operazione-trasparenzadati-on-line_4041e56f-1131-44af-a502-9c893223b62f.html

Questa repository continuerà comunque ad essere aggiornata o verrà dismessa?
Grazie

**Comment by CapMar00** [comment]
Chiudo perché ho visto che si tratta di un pdf settimanale:
https://www.governo.it/sites/governo.it/files/documenti/documenti/Notizie-allegati/covid-19/reportVaccinazioni260321.pdf
quindi suppongo che il github verrà ancora aggiornato.
Grazie

**Comment by RossoDeM** [comment]
> Buonasera,
> l'ANSA annuncia che da domani i dati sui vaccini saranno consultabili sul sito della presidenza del Consiglio per Regione e categoria
> https://www.ansa.it/sito/notizie/topnews/2021/03/25/vaccini-da-domani-operazione-trasparenzadati-on-line_4041e56f-1131-44af-a502-9c893223b62f.html
> 
> Questa repository continuerà comunque ad essere aggiornata o verrà dismessa?
> Grazie

Beh, direi... Visto che alla fine non sono altro che banali pdf con tabelline che aggiungono ben poco, anzi.
Ribadisco che questo repository deve al più presto fornire dataset giornalieri.
