### ISSUE TITLE
Ora legale e orario in last-update-dataset.json

### ISSUE THREAD

**Issue by CapMar00** [italia/covid19-opendata-vaccini#123]
Buongiorno,
con il passaggio all'ora legale l'orario di aggiornamento del file risulta essere 2 ore in anticipo rispetto all'effettivo caricamento dei dati.
Si può ovviare alla cosa?
grazie

**Comment by lucabruno300** [comment]
Non gestisco la repository, però nel json viene specificato il GMT +00:00. Quindi l'ora indicato sul json è corretta considerando che con l'ora legale ci troviamo 2 ore in avanti rispetto al meridiano di Greenwich (GMT +02:00). Nel tuo applicativo puoi correggerlo quindi.
Perchè il fuso orario considerato è quello immagino sia per le impostazioni di default che utilizza il tool di update.

**Comment by CapMar00** [comment]
> Non gestisco la repository, però nel json viene specificato il GMT +00:00. Quindi l'ora indicato sul json è corretta considerando che con l'ora legale ci troviamo 2 ore in avanti rispetto al meridiano di Greenwich (GMT +02:00). Nel tuo applicativo puoi correggerlo quindi.
> Perchè il fuso orario considerato è quello immagino sia per le impostazioni di default che utilizza il tool di update.

Grazie, hai ragione. disattenzione mia che non avevo valutato il formato data correttamente.
