### ISSUE TITLE
Cambio nome vaccino AstraZeneca

### ISSUE THREAD

**Issue by camicius** [italia/covid19-opendata-vaccini#137]
Cosa serve avere un Changelog (e tenerlo popolato) quando vengono poi fatti cambi di nome (inutili all'atto pratico) senza avvertire? 

Capisco che il vaccino di AstraZeneca abbia cambiato nome, però era davvero necessario da un giorno con l'altro senza avvertire cambiarlo nei repository?

**Comment by CapMar00** [comment]
Buongiorno,
concordo che sarebbe stato importante avvertire, è una modifica che può compromettere gli script di interrogazione.

**Comment by tsmagnum** [comment]
Concordo, nel mio caso oltretutto l'utilizzo delle parentesi tonde nel nome sta rendendo difficile l'utilizzo dei dati.

**Comment by LBreda** [comment]
A questo proposito, credo sia utile a molti un dataset con i nomi correnti dei fornitori autorizzati, eventualmente prima ancora che i loro vaccini siano disponibili. Banalmente è stato autorizzato il vaccino Johnso&Johnson ma non è dato di sapere come si chiamerà nel dataset quando inizierà ad esserci.

**Comment by paolo-restuccia** [comment]
@LBreda in realtà il vaccino Johnson&Johnson è già presente nel file `consegne-vaccini-latest.csv` con il nome "Janssen" con delle consegne fittizzie (il campo `numero_dosi` è vuoto) avvenute in data 01-03-2021.

**Comment by LBreda** [comment]
Grazie mille @paolo-restuccia, non lo avevo notato

**Comment by paolo-restuccia** [comment]
@LBreda di nulla! Se queste cose venissero annunciate nel Changelog, come dovrebbe essere, non bisognerebbe basarci su quello che si nota per caso cercando dentro i vari file. 😃

**Comment by jrkager** [comment]
Inoltre mi sembra poco consistente con gli altri nomi, siccome il fornitore resta comunque "AstraZeneca" e solo il nome del vaccino con quale lo vendono è cambiato in ["Vaxzevria".](https://en.wikipedia.org/wiki/Oxford–AstraZeneca_COVID-19_vaccine) (cf. il vaccino di Pfizer/BioNTech viene anche venduto sotto il nome di ["Corminaty"](https://en.wikipedia.org/wiki/Pfizer–BioNTech_COVID-19_vaccine))

**Comment by camicius** [comment]
Non dargli idee strane che se no cambiano di nuovo e dobbiamo, di nuovo, corrergli dietro. ;-)
