### ISSUE TITLE
fornitore Janssen

### ISSUE THREAD

**Issue by GabM3** [italia/covid19-opendata-vaccini#143]
forse si intente johnson and johnson
![Schermata 2021-04-12 alle 10 34 31](https://user-images.githubusercontent.com/47599579/114365317-ac105900-9b7a-11eb-8d59-65d54e8af998.png)

**Comment by mzzntn** [comment]
https://www.janssen.com/italy/

**Comment by GabM3** [comment]
> https://www.janssen.com/italy/

ora lo so, grazie :D
