### ISSUE TITLE
Somministrazioni per fasce di età, nel tempo

### ISSUE THREAD

**Issue by leonardopetrini** [italia/covid19-opendata-vaccini#147]
Buongiorno, chiedo se è possibile avere i dati sulla somministrazione di vaccini per fasce di età in funzione del tempo. 

Ora sono disponibili solo i dati aggregati nel tempo per fascia di età (latest), oppure quelli nel tempo ma suddivisi per categorie in cui la fascia di età entra solo 80+ o no.

Grazie!

**Comment by camicius** [comment]
Puoi farlo aggregando i dati  come vuoi, usando varie tecnologie, da una pivot su excel, all'importazione su un database e successive query. 
Un dato aggregato non è separabile, un dato disaggregato puoi sommarlo come preferisci.

**Comment by leonardopetrini** [comment]
Chiaro, non mi ero accorto fosse presente la colonna "fascia anagrafica" nei dati disaggregati, ho visto solo ora, grazie!

**Comment by Bloodyblade49** [comment]
Ma non esiste una repository _anagrafica-vaccini-summary-latest_  per ogni regione? Sarebbe molto interessante vedere il numero di prime e seconde dosi somministrate ad ogni fascia d'età a livello regionale, e non solo in generale a tutti i vaccinati.
