### ISSUE TITLE
Suddividere i dati per giorno solare

### ISSUE THREAD

**Issue by carmelolg** [italia/covid19-opendata-vaccini#15]
A partire dall'ottimo lavoro svolto su [questa repository](https://github.com/pcm-dpc/COVID-19), mi chiedevo se fosse possibile:

1. Suddividere i dati giornalieri su più file
2. Pubblicare un aggiornamento quotidiano in una determinata fascia oraria

Il resto delle richieste sono state fatte in altre _issues_.

Grazie

**Comment by fotografAle** [comment]
Mi associo a questa richiesta.
Il dato che servirebbe al mio sistema previsionale sarebbe solo il cumulato quotidiano nazionale. Attualmente lo ricavo da: https://github.com/italia/covid19-opendata-vaccini/blob/master/dati/somministrazioni-vaccini-summary-latest.csv
Ho notato, però, che i dati variano continuamente; anche quelli dei giorni passati. Questa situazione non è molto gradita dall'algoritmo di DL.
Grazie della cortese attenzione e per il prezioso lavoro e saluti,
Alessandro

**Comment by fracuci** [comment]
Spero anche io si possa avere questo dato. Come @carmelolg anche io utilizzo il giorno per fare la get dei dati dallo stesso repository mettendoli a disposizione per il mio bot Telegram. Servirebbe anche sapere l'ora di update dei dati

**Comment by datateam-opendata** [comment]
Grazie @carmelolg per questa issue. 
Per quanto riguarda il punto 1, il sistema di analisi dei dati è in fase di aggiornamento evolutivo. In questo momento si stanno valutando modifiche alla base dati e cercheremo di tener presente questa segnalazione per migliorare la fruibilità del dataset. 
Anche per quanto concerne il punto 2 vi sarà una modifica dello scheduler non appena il nuovo sistema sarà live.
Sarà disponibile una roadmap all'interno di questo repository.

**Comment by carmelolg** [comment]
Grazie mille @datateam-opendata 
Rimango aggiornato.

Buon lavoro,
Carmelo

**Comment by carmelolg** [comment]
chiudo poiché non più rilevante.
