### ISSUE TITLE
Tipologia vaccino (consegnato e somministrato)

### ISSUE THREAD

**Issue by diabolicus23** [italia/covid19-opendata-vaccini#16]
Visto che diversi vaccini hanno diverso intervallo tra le due dosi (e J&J forse sarà monodose) sarebbe utile sapere quale vaccino viene somministrato e quanti, di ciascuna tipologia, vengono consegnati.
Chiaramente in vista della prossima settimana in cui inizieremo a ricevere Moderna.

**Comment by lvegro** [comment]
ciao, cfr issue #7

**Comment by datateam-opendata** [comment]
Grazie @diabolicus23 per la issue. Essendo strettamente correlata alle #7, possiamo ritenerla risolta. Grazie ancora.
