### ISSUE TITLE
Cancellazione di tutti i dati?

### ISSUE THREAD

**Issue by tommasorigon** [italia/covid19-opendata-vaccini#160]
Buongiorno,

I dati delle vaccinazioni sembrano essere scomparsi per errore dopo l'ultimo commit. I file non hanno contenuto.

**Comment by marcosolina** [comment]
![image](https://user-images.githubusercontent.com/26163844/116450844-13592900-a85c-11eb-8e29-cfcc0f541318.png)

**Comment by FrancescoDiMaggio** [comment]
Sembra che i dati al momento siano raggiungibili, @tommasorigon confermi?

![image](https://user-images.githubusercontent.com/10175883/116466395-b450df80-a86e-11eb-9b92-bb7b234ae541.png)

**Comment by tommasorigon** [comment]
@FrancescoDiMaggio Si, sono tornati online.
