### ISSUE TITLE
Tutti i vaccini

### ISSUE THREAD

**Issue by passani** [italia/covid19-opendata-vaccini#164]
Salve, data scientist amatoriale. Probabile che la mia sia una domanda sciocca. In quel caso scusate.

Questi dati rappresentano la totalita' dei vaccini somministrati in italia? Oppure esistono dei canali di somministrazione che non vengono contati qui?

Secondo questo grafico, tra prime e seconde dosi si arriva a 500k somministrazioni al giorno, ma non tutti i giorni (e in particolare non nei weekend). Capisco male qualcosa? Grazie 

    plt.figure(figsize=(15,8))
    plt.xticks(rotation=70)
    sns.lineplot(x=df.index, y="prima_dose", data=df, estimator=sum, ci=None)
    sns.lineplot(x=df.index, y="seconda_dose", data=df, estimator=sum, ci=None);`

![image](https://user-images.githubusercontent.com/468516/117673396-c38e3200-b178-11eb-9d4f-6c5daf638c2a.png)

**Comment by bendolaccio** [comment]
Tutto giusto! L'andamento è davvero quello. Con dei cali vertiginosi delle somministrazioni nei giorni festivi e dei tentativi di raggiungere il numero di dosi prefissato dal generale Figliuolo durante la settimana. In realtà la media su 7 giorni non è neanche malissimo perché siamo intorno ai 460.000, ma ancora non basta. Purtroppo le dosi non arrivano, e lì ci si può fare poco: non si può inoculare quello che non si ha

**Comment by passani** [comment]
Grazie Bendolaccio. Questa ti sembra la via giusta di calcolare e visualizzare la media?

![image](https://user-images.githubusercontent.com/468516/118127874-350fef80-b3c8-11eb-908d-7e89fb65f63e.png)

**Comment by bendolaccio** [comment]
Sì, perfetto!
