### ISSUE TITLE
Errore in update

### ISSUE THREAD

**Issue by Paulsword** [italia/covid19-opendata-vaccini#165]
L'ultimo aggiornamento su alcuni file è errato (aggiornato al 9 maggio) o del tutto vuoto

**Comment by doherbr** [comment]
somministrazioni-vaccini-summary-latest.csv  è vuoto.

**Comment by AAAlessandroP** [comment]
già

**Comment by massimomartucci** [comment]
su somministrazioni-vaccini-latest.csv ci sono solamente 3079 record, su alcuni giorni casuali

**Comment by itsmatteomanf** [comment]
https://github.com/italia/covid19-opendata-vaccini/commit/61afeb1c54b52c2268a8ba17d4b2abfe7fb1e507 sembra risolvere.
