### ISSUE TITLE
Distinzione dosi somministrazioni-vaccini-latest

### ISSUE THREAD

**Issue by dennisangemi** [italia/covid19-opendata-vaccini#169]
È normale che non vengano più popolati i campi "prima_dose" e "seconda_dose" del file [somministrazioni-vaccini-latest.csv](https://github.com/italia/covid19-opendata-vaccini/blob/master/dati/somministrazioni-vaccini-latest.csv) ?

**Comment by LorenzoRuff** [comment]
Ma non hanno smesso di popolarli. Sono come sempre.

**Comment by aborruso** [comment]
Ciao @dennisangemi [guardando il file](https://flatgithub.com/italia/covid19-opendata-vaccini?filename=dati%2Fsomministrazioni-vaccini-latest.csv&filters=area%3Dsic&sha=9e6a9f4a150e6b96ef52827e0e2692274d68701e&sort=data_somministrazione%2Cdesc&stickyColumnName=data_somministrazione) non ci vedo nulla di strano? 

Cosa non ti torna?

**Comment by dennisangemi** [comment]
Grazie millle @LorenzoRuff e @aborruso , evidentemente dopo il cambiamento del dataset il mio sheet fa i capricci. Provo a risolvere. Grazie ancora e scusate!

(p.s. @aborruso quel magheggio con flatgithub è spaziale)
![image](https://user-images.githubusercontent.com/77018886/120283433-7acf2200-c2bb-11eb-8cf6-a8e749db8711.png)
