### ISSUE TITLE
Calcolo monodose Janssen

### ISSUE THREAD

**Issue by GrayNeel** [italia/covid19-opendata-vaccini#180]
Salve a tutti,

ho un enorme problema con il calcolo delle persone che hanno completato il ciclo vaccinale.

Esso dovrebbe essere la somma di
`TOTALE_SECONDA_DOSE + TOTALE_INFEZIONI_PREGRESSE + TOTALE_MONODOSE_JANSSEN`

ma mi è impossibile reperire il dato `TOTALE_MONODOSE_JANSSEN` poiché il file `somministrazioni-vaccini-latest.json` è troppo grande per il mio programma in PHP e quest'ultimo va OutOfMemory se provo a scandirlo.

Dunque, è possibile reperire tale dato in altro modo?
Sarebbe fattibile inserire tra questi file anche un conteggio sulle dosi dei vari tipi di vaccino "summary" (cioè in file di breve lunghezza come ad esempio `anagrafica-vaccini-summary-latest.json`)?

**Comment by CapMar00** [comment]
ciao,
hai già provato a processarlo con questa libreria?
https://opensource.box.com/spout/

**Comment by GrayNeel** [comment]
Ottengo, purtroppo, lo stesso errore.
![immagine](https://user-images.githubusercontent.com/44164482/124563744-9c827280-de40-11eb-98d4-a5c889ca8b69.png)

**Comment by camicius** [comment]
Nel php.ini dovresti trovare qualcosa del genere
memory_limit = 256M
e puoi portarlo a 512M, soprattutto se non è online.

Altrimenti più radicalmente puoi mettere tutto dentro un db sqlite ed eseguire le select direttamente da lì.

**Comment by GrayNeel** [comment]
Grazie mille, ho risolto!
