### ISSUE TITLE
Numero Seconde dosi > Numero Prime dosi over 50

### ISSUE THREAD

**Issue by fede4096** [italia/covid19-opendata-vaccini#187]
Ciao,

segnalo un problema che ho rilevato nel calcolo di prime e seconde dosi per cui le seconde eccedono le prime (depurate dalle dosi J&J). In particolare. ad oggi, nelle seguenti regioni mi risultano limitatamente agli **over 50** questi numeri:

- **Lombardia**: 3.425.872 seconde dosi - 3.356.678 prime dosi
- **Lazio**: 2.043.933 seconde dosi - 2.039.940 prime dosi
- **Umbria**: 329.944 seconde dosi - 328.518 prime dosi

Com'è possibile? Semplici errori (miei o alla fonte) o altro? Faccio notare che è da almeno 10 giorni che sussiste questo problema.

Grazie in anticipo per le risposte

**Comment by LorenzoRuff** [comment]
Non è così. Nelle tre regioni le prime dosi sono di più delle seconde dosi (con numeri molto diversi).

Togliendo Janssen dalle prime dosi si ha:
- Lombardia: 5.379.897 seconde, 6.480.759 prime
- Lazio: 3.069.087 seconde, 3.544.429 prime
- Umbria: 447.814 seconde, 539.152 prime

**Comment by LorenzoRuff** [comment]
Non è così. Togliendo Janssen dalle prima dosi si ha per gli over 50 (seconde e prime dosi): 

- Lombardia: 3.425.872 - 3.621.521
- Lazio: 2.043.933 - 2.146.989
- Umbria: 329.944 - 346.316.

Tu invece stai togliendo due volte Janssen dalle prime dosi.
