### ISSUE TITLE
Pubblicare anche i dati disaggregati

### ISSUE THREAD

**Issue by aborruso** [italia/covid19-opendata-vaccini#2]
La dashboard espone anche dati disaggregati per data, e punto di somministrazione (vedi immagine di sotto).

Anche questi sarebbe opportuno e utile pubblicarli qui.

Grazie

![image](https://user-images.githubusercontent.com/30607/103669740-05179200-4f79-11eb-9cf3-88341b8fbdbf.png)

**Comment by LBreda** [comment]
Non solo. Il dataset `somministrazioni-vaccini-latest` è letteralmente terrficante. I numeri indicano piú volte gli stessi vaccinati ed è impossibile disaggregarli (ad esempio volendo avere il dato dei, che so, "operatori sanitari uomini").

**Comment by zab0v** [comment]
Condivido le richieste di Andrea e Lorenzo.

Diciamo che se le tabelle così strutturate possono essere adatte ad una lettura "umana", sarebbe utile presentare (anche) i dati come dati, in modalità "row", per consentire alle macchine di interpretare il cubo... e pivotarlo.

Ad esempio, il dataset "somministrazioni-vaccini-latest.*" presenta 5 dimensioni e una misura:
1. data_somministrazione (frequenza giornaliera, fino al termine della campagna)
2. area (20 modalità)
3. fascia_anagrafica (9 modalità)
4. sesso (2 modalità)
5. categoria (3 modalità)
E infine le somministrazioni... cioè la misura osservata

Il tutto, naturalmente, omettendo sia i totali, sia le righe con osservazioni pari a zero.

Esempio:
data;area;fascia_anagrafica;sesso;categoria;somministrazioni
2020-12-27;ABR;16-19;F;OS;999

Grazie :)

**Comment by zab0v** [comment]
Condivido le richieste di Andrea e Lorenzo.

Diciamo che se le tabelle così strutturate possono essere adatte ad una lettura "umana", sarebbe utile presentare (anche) i dati come dati, in modalità "row", per consentire alle macchine di interpretare il cubo... e pivotarlo.

Ad esempio, il dataset "somministrazioni-vaccini-latest.*" presenta 5 dimensioni e una misura:
1 - data_somministrazione (frequenza giornaliera, fino al termine della campagna)
2 - area (20 modalità)
3 - fascia_anagrafica (9 modalità)
4 - sesso (2 modalità)
5 - categoria (3 modalità)
E infine le somministrazioni... cioè la misura osservata

Il tutto, naturalmente, omettendo sia i totali, sia le righe con osservazioni pari a zero.

Esempio:
data;area;fascia_anagrafica;sesso;categoria;somministrazioni
2020-12-27;ABR;16-19;F;OS;999

Grazie :)

**Comment by datateam-opendata** [comment]
Grazie @aborruso per la issue. I dati sono forniti con aggregazione regionale e al momento la nostra roadmap non considera l'eventualità di disaggregarli. Provvediamo a chiudere la issue. Segnaleremo eventuali modifiche nelle scelte di aggregazione del dato. Grazie ancora

**Comment by aborruso** [comment]
> Grazie @aborruso per la issue. I dati sono forniti con aggregazione regionale e al momento la nostra roadmap non considera l'eventualità di disaggregarli. Provvediamo a chiudere la issue. Segnaleremo eventuali modifiche nelle scelte di aggregazione del dato. Grazie ancora

Grazie a voi @datateam-opendata 

Non so se ho compreso bene: pubblicate i dati aggregati, perché così li ricevete. 
Se è così, chi vi fornisce i dati? Lo chiedo in modo da direzionare questa richiesta al responsabile dati.

Grazie ancora
