### ISSUE TITLE
Molise dosi aggiuntive maggiori della platea

### ISSUE THREAD

**Issue by Rabelaiss** [italia/covid19-opendata-vaccini#204]
La somma delle dosi aggiuntive del Molise nel file somministrazioni-vaccini-latest.csv è 8784, la relativa platea nel file platea-dose-aggiuntiva.csv è 7055. Qualcuno ha ricevuto più di una dose aggiuntiva o la platea è da aggiornare?

**Comment by gliv60** [comment]
Non è il solo caso. La Campania è oltre al 200%, la Sicilia quasi al 200%, e molte altre ben al di sopra del 100%
