### ISSUE TITLE
Rimuovere righe "aggregate" da somministrazioni-vaccini-summary-latest

### ISSUE THREAD

**Issue by aborruso** [italia/covid19-opendata-vaccini#21]
La risorsa `somministrazioni-vaccini-summary-latest` contiene una riga che è somma di altre presenti, ovvero quella in cui `area
=="ITA"`. Non dovrebbe essere così.

Inoltre si mescolano nello stesso campo due categorie amministrative gerarchicamente diverse.

Rimuoverei queste righe.

Grazie

**Comment by CapMar00** [comment]
l'importante se si decide di rimuovere le righe ITA di somministrazioni-vaccini-summary-latest è avvisare con congruo anticipo per dar modo di aggiornare gli script di chi ormai ci si è agganciato 😉
grazie



> La risorsa `somministrazioni-vaccini-summary-latest` contiene una riga che è somma di altre presenti, ovvero quella in cui `area =="ITA"`. Non dovrebbe essere così.
> 
> Inoltre si mescolano nello stesso campo due categorie amministrative gerarchicamente diverse.
> 
> Rimuoverei queste righe.
> 
> Grazie

**Comment by aborruso** [comment]
Risolto con https://github.com/italia/covid19-opendata-vaccini/commit/0cd3915d150d01e801d5d8db561b00faece33d52#diff-4d864b9acc5d90ed06a3616387f5be4c33490b8c3dcb0db57399bc23828a2a20
