### ISSUE TITLE
Add information about the type of doses administered (first or second dose) / informazioni su tipo di dose somministrata (prima o seconda)

### ISSUE THREAD

**Issue by lvegro** [italia/covid19-opendata-vaccini#22]
When 1-dose vaccines become available, it will be important to distinguish between initial inoculations and boosters. It would be useful if a new variable is added to keep track of this information for each region/vaccination point.
Thank you!

-----------------------------------

Quando saranno disponibili i vaccini monodose, sarà importante distinguere tra le prime inoculazioni e i richiami. Sarebbe utile se venisse aggiunta una variabile per tener traccia di questa informazione per ogni regione/punto di vaccinazione.
Grazie!

**Comment by aborruso** [comment]
Questa la chiuderei e nel caso mi aggancerei a [questa precedente](https://github.com/italia/covid19-opendata-vaccini/issues/12)

**Comment by lvegro** [comment]
concordo, grazie per la segnalazione
