### ISSUE TITLE
Aumento anomalo dati FVG

### ISSUE THREAD

**Issue by Rabelaiss** [italia/covid19-opendata-vaccini#228]
Dal commit del 4 feb 2022, 08:06 (ab1b5461827a29d3365ef8b91498dbd867da7ce1) a quello del 5 feb 2022, 01:08 (da5ea9cd7a2e173034a1008314c496eae3efaf8f) i dati del FVG relativi al periodo dal 2020-12-27 al 2022-02-03, sono aumentati in modo considerevole

```
prima_dose                  962997 -> 1107651 (+15%)
seconda_dose                889353 -> 1005020 (+13%)
pregressa_infezione          47335 -> 54870 (+16%)
dose_addizionale_booster    675027 -> 701484 (+4%)
```

La % di persone vaccinate con almeno 1 dose (prima dose + pregressa infezione) è aumentata dal 87% a oltre il 100% (la popolazione vaccinabile è 1.161.352).

Confrontando i grafici dei due commit si nota che l'aumento ha coinvolto i dati su tutto il periodo, in particolare primavera/estate 2021. Vista l'entità dell'aumento, sembra si tratti di un errore più che di un riconteggio.

Sono usciti avvisi a riguardo da qualche parte?

![Webp net-gifmaker](https://user-images.githubusercontent.com/20670578/152692127-4946fb16-9262-4df4-954c-ef3377707b23.gif)

**Comment by peppedorio** [comment]
Ancora nessuna notizia? i dati sembrano fuori scala. @Rabelaiss grazie per la segnalazione
