### ISSUE TITLE
Nuovo file platea-second-booster identico a platea-dose-addizionale-booster

### ISSUE THREAD

**Issue by m-melis** [italia/covid19-opendata-vaccini#232]
La platea indicata nel file "pleatea-second-booster" risulta identica a quella indicata nel file "platea-dose-addizionale-booster". Evidentemente un errore.

Inoltre, perchè avete usato l'inglese in questo caso? Platea-SECOND-booster...

**Comment by Rabelaiss** [comment]
ma la `booster_immuno` e la `2nd_booster` vanno entrambe considerate come quarta dose?

**Comment by m-melis** [comment]
> ma la `booster_immuno` e la `2nd_booster` vanno entrambe considerate come quarta dose?

Si. "booster_immuno": Numero somministrazioni dose booster a soggetti che hanno già completato il ciclo vaccinale primario con tre dosi (di cui la terza addizionale), dopo un intervallo minimo di almeno quattro mesi (120 giorni) dalla dose addizionale stessa.

**Comment by m-melis** [comment]
Il file pleatea-second-booster è stato aggiornato, e sembra contenere dati coerenti.

Altra incongruenza introdotta però, hanno utilizzato categorie diverse da quelle del file "platea-dose-addizionale-booster", ovvero Fragili, Ospiti RSA e Over 80 anzichè le fasce di età. Ma questo è un altro problema.
