### ISSUE TITLE
A proposito dell'ultimo changelog: rilasciare un file di mapping delle tantissime variazioni

### ISSUE THREAD

**Issue by aborruso** [italia/covid19-opendata-vaccini#234]
Buongiorno,
avete [annunciato](https://github.com/italia/covid19-opendata-vaccini/blob/e67918e7378206cc7df5f9ee059b3310fce38ed3/Changelog.md#20052022) delle importanti modifiche sui nomi dei campi di tante tabelle.

Decine e decine di applicazioni sfruttano queste basi dati, queste modifiche hanno un grosso impatto.

Per una modifica così importante e ricca dovreste pubblicare anche un file _machine readable_ che mappi le modifiche da fare in _bulk_, e non soltanto un elenco puntato.

Qualcosa come

```json
{
  "file": "consegne-vaccini-latest",
  "campi": [
    {
      "old-name": "fornitore",
      "new-name": "forn"
    },
    {
      "old-name": "codice_NUTS1",
      "new-name": "N1"
    }
  ]
}
```

Ma anche un semplice CSV, con una struttura come quella di sotto

| file | old-name | new-name|
|---|---|---
| consegne-vaccini-latest | fornitore | forn|
| consegne-vaccini-latest | codice_NUTS1 | N1|

Sono sicuro che concorderete sulla necessità di questa integrazione.

Grazie

**Comment by m-melis** [comment]
Incredibile.

Comunque, purtroppo, visti i precedenti dubito ci saranno integrazioni/miglioramenti della modifica annunciata. Felice di essere smentito.

**Comment by floatingpurr** [comment]
Quella di @aborruso mi pare un'ottima idea per mitigare l'impatto (pesantissimo) delle modifiche sulla nomenclatura dei descrittori dei dati. Perlomeno, le applicazioni che consumano queste informazioni potrebbero utilizzare i file di mapping per rinominare i dati secondo il vecchio formato, garantendo la retrocompatibilità.

In alternativa, ci potrebbe anche stare un repo parallelo community-driven che prende i dati da questo e li riformatta nel vecchio stile.

**Comment by aborruso** [comment]
Ottima nota @floatingpurr 


Speriamo che la mia nota venga accolta

**Comment by floatingpurr** [comment]
Sì @aborruso! A maggior ragione, visto che la modifica pare inevitabile, un **mapping strutturato** sarebbe il minimo per mitigare l'impatto di tutto ciò.

**Comment by alusiani** [comment]
A me sembra che JSON non sia un formato adatto per gestire grandi quantita' di dati, specialmente se viene usata una struttura non ottimizzata in cui identificatori identici vengono ripetuti per ogni microdato. Anche l'idea di avere un grande file cui si fanno delle modifiche usando il sistema di revisione di github mi sembra una cattiva idea in presenza di quandi quantita' di dati. In queste condizioni sarebbe utile pensare a organizzare i dati in file separati di dimensioni medie e non grandi, e possibilmente con formati interni non eccessivamente ridondanti.

**Comment by aborruso** [comment]
Creato file di mappatura https://github.com/italia/covid19-opendata-vaccini/issues/236
