### ISSUE TITLE
richiesta chiarimenti su modifiche 20 maggio

### ISSUE THREAD

**Issue by CapMar00** [italia/covid19-opendata-vaccini#235]
Buongiorno,
vorrei chiedere un paio di chiarimenti in merito alle modifiche previste per il 20 maggio:

1. scrivete che "Il campo nome_regione sarà rinominato in reg".
Al momento mi sembra di non vedere un campo `nome_regione` ma solo `nome_area`, confermate che la modifica sarà effettuata su quello e che sarà `nome_area` => `reg` ?

2. dato per affermativo il punto 1: nel changelog fra i file che subiranno la modifica da `nome_regione/nome_area` a `reg` non indicate i 4 file relativi alle platee che pure hanno quel campo. Prevedete di uniformare anche quelli al resto anche se non li avete messi nell'elenco del changelog o resteranno con `nome_area` ? 

3. scrivete che "il campo data_somministrazione diventerà di tipo date".
Questo implica che cambierà formato o resterà comunque nell'attuale yyyy-mm-dd ?

Grazie

**Comment by m-melis** [comment]
> 3\. scrivete che "il campo data_somministrazione diventerà di tipo date".
>     Questo implica che cambierà formato o resterà comunque nell'attuale yyyy-mm-dd ?

In https://github.com/italia/covid19-opendata-vaccini#descrizione-dataset il campo `data_somministrazione` è definito come datetime, ma poi nei file è effettivamente solo un date. Quindi non ha molto senso effettivamente quella nota...

**Comment by vi-enne** [comment]
La più recente versione del [Changelog ](https://github.com/italia/covid19-opendata-vaccini/blob/e9f35e3660a0547214fd3d82573e3216f64e9aa0/Changelog.md)dovrebbe rispondere ai punti 1 e 2.

![image](https://user-images.githubusercontent.com/44818674/168596277-3db5d5f7-4a51-46dc-9514-7aff011871b2.png)
