### ISSUE TITLE
Utilizzo in Microsoft Power BI Desktop

### ISSUE THREAD

**Issue by PBra** [italia/covid19-opendata-vaccini#24]
Qualcuno sa dirmi come caricare i dati direttamente in un report costruito con Microsoft Power BI Desktop?
Grazie

**Comment by gilegiov** [comment]
Devi utilizzare un'origine dati "web" ed incollare l'indirizzo del file "raw" corrispondente da questo repository. 
Ciao.

**Comment by PBra** [comment]
Grazie.
Funziona

Il giorno lun 11 gen 2021 alle ore 10:05 Marco <notifications@github.com>
ha scritto:

**Comment by datateam-opendata** [comment]
Ciao @PBra siccome il problema sembra essere rientrato, provvediamo a chiudere la issue. Non esitare a riaprirla se dovessi avere problemi sui dataset qui esposti. Grazie.
