### ISSUE TITLE
Errore data vaccino (parte 2)

### ISSUE THREAD

**Issue by vi-enne** [italia/covid19-opendata-vaccini#28]
E' presente di nuovo lo stesso errore sulla data di alcuni vaccinati (1970-01-01).
Suggerisco di implementare un controllo visto che e' la seconda volta che accade.

Edit: aggiungo schermata
![image](https://user-images.githubusercontent.com/44818674/104360820-a2c21280-54df-11eb-9de9-6fed88815963.png)

**Comment by datateam-opendata** [comment]
Grazie molte @vi-enne abbiamo provveduto a correggere il dato e ad implementare, come giustamente suggerito, una serie di controlli aggiuntivi. Grazie ancora.

**Comment by vi-enne** [comment]
Grazie a voi!
Fa piacere avere riscontro alle issue :)

Grazie ancora per gestire questa utilissima repo
