### ISSUE TITLE
somministrazioni-vaccini-latest.csv: spazi ridondanti da rimuovere

### ISSUE THREAD

**Issue by aborruso** [italia/covid19-opendata-vaccini#31]
Buonasera,
nel file in oggetto (verificato fino a [questo momento del versioning](https://github.com/italia/covid19-opendata-vaccini/blob/261ac5d91f2e6ca1a90f4cf36ee71124a8fcd758/dati/somministrazioni-vaccini-latest.csv)) ci sono diverse celle in cui c'è da rimuovere qualche spazio. Credo soltanto in `fascia_anagrafica`.

In questo diff un esempio legato all'ultima versione, poi corretta da me: https://gist.github.com/aborruso/9c8e53bf7aa03bd6d29cc9840265b550/revisions

Grazie

**Comment by datateam-opendata** [comment]
Grazie @aborruso per l'importante segnalazione. stiamo provvedendo a correggere il problema alla fonte. Quando la correzione verrà apportata, ti faremo sapere. Grazie ancora.

**Comment by datateam-opendata** [comment]
Grazie @aborruso abbiamo corretto il dato alla fonte. Provvedo a chiudere la issue. Grazie ancora
