### ISSUE TITLE
Dosi somministrate !== persone vaccinate ?

### ISSUE THREAD

**Issue by gagginaspinnata** [italia/covid19-opendata-vaccini#32]
Cerco di spiegarmi meglio possibile. Al momento in italia sono state somministrate circa 1,000,000 di dosi di vaccino. Significa che ci sono 1,000,000 di persone già vaccinate ed immunizzate, oppure che sono state somministrate 1,000,000 di dosi di vaccino e che verosimilmente abbiamo mezzo milione di persone vaccinate ed immunizzate (considerando che per una vaccinazione completa ci vogliono 2 dosi)?

I dati relativi alle dosi somministrate fanno riferimento alle vaccinazioni parziali, oppure alle persone già vaccinate completamente con, ad esempio, prima dose + richiamo?

**Comment by FrancescoBernardii** [comment]
Ad oggi (14/01) nessuno dovrebbe aver ricevuto la seconda dose. Quindi per ora il numero si riferisce a dosi somministrate (=numero di persone che ha ricevuto la prima dose). 

C'è un altro issue aperto per includere il numero di vaccinati totali (prima + seconda dose): #12

**Comment by gagginaspinnata** [comment]
Grazie mille, ora è tutto più chiaro. Spero che venga aggiunta anche qualche informazione sulle persone vaccinate (prima + seconda dose). Penso sia in assoluto il dato più importante

**Comment by datateam-opendata** [comment]
Ciao @gagginaspinnata siccome questa issue è un duplicato di #12 la chiudiamo e ti consigliamo di seguire l'altra discussione. Grazie
