### ISSUE TITLE
Column "data_consegna" removed from "consegne-vaccini-latest.csv"

### ISSUE THREAD

**Issue by UnfoldingBI** [italia/covid19-opendata-vaccini#35]
Hi,
column "data_consegna" seems to have been removed from the specified file

Is it possible to restore it?

**Comment by FrancescoBernardii** [comment]
Are you sure? Looks like it's there. Maybe the addition of the new column "fornitore" has changed the position of that column. 

![image](https://user-images.githubusercontent.com/60037690/104811153-e6778d80-57f9-11eb-8f5f-e36e718f4836.png)

**Comment by UnfoldingBI** [comment]
You are correct. The addition of the new column moved the "data_consegna" column and this messed up my script 

I should have checked before opening the issue. My mistake. Thanks for your support.
