### ISSUE TITLE
Oltre 2mila dosi somministrate a personale sanitario ultra 80enne

### ISSUE THREAD

**Issue by diabolicus23** [italia/covid19-opendata-vaccini#40]
Al momento della verifica (circa le ore 23.00 del 17/01/2021) risultano somministrate 2023 dosi a personale sanitario nella fascia 80+ (precisamente 1606 nella fascia 80-89 e 417 nella fascia 90+).
È possibile capire se questo dato è relativo a persone che rientrano realmente tra il personale sanitario (e se sì, si parla di personale attivo?) o se si può trattare, anche solo in parte, di errori in fase di data entry o comunicazione dalle Regioni?

**Comment by datateam-opendata** [comment]
Grazie @diabolicus23 per la issue. Il dato è in fase di consolidamento ed eventuali errori sono segnalati alle Regioni. Grazie ancora.
