### ISSUE TITLE
Seconde dosi sin dal primo giorno della campagna vaccinale

### ISSUE THREAD

**Issue by diabolicus23** [italia/covid19-opendata-vaccini#41]
Nel file somministrazioni-vaccini-latest.csv compaiono numerose seconde dosi somministrate a partire dal primo giorno (27/12/2020) quando mi aspetterei di trovarle a partire dal 17/01/2021 (21gg dopo la prima somministrazione).

**Comment by datateam-opendata** [comment]
Grazie @diabolicus23 per l'importante segnalazione. La base dati è in fase di consolidamento e segnalazioni di questo genere ci aiutano a migliorare la qualità del dato fornito. Grazie ancora.
