### ISSUE TITLE
Problema categoria over 80

### ISSUE THREAD

**Issue by LorenzoRuff** [italia/covid19-opendata-vaccini#42]
Nella nuova categoria degli over 80 risultano esserci persone che hanno meno di 80 anni.

![image](https://user-images.githubusercontent.com/59303550/105000639-da284600-5a2e-11eb-8bc4-6df7dbf7fa25.png)

**Comment by FrancescoBernardii** [comment]
Seguo, e aggiungo: si potrebbe avere un chiarimento sulla differenza tra "categoria_personale_non_sanitario" e "categoria_over_80"?
Nel caso in cui la prima si riferisca, in senso generale, a tutto il resto della popolazione (non oss, e non ospite di rsa), ci sarebbe una sovrapposizione con "categoria_over_80" (per i dati in fascia_anagrafica = 80-89/90+).

Vi sarei grato se poteste chiarire. 
Grazie

**Comment by daniloderosa** [comment]
<img width="1201" alt="Schermata 2021-01-19 alle 15 01 17" src="https://user-images.githubusercontent.com/74054364/105044916-956cd100-5a67-11eb-8e83-124ea4cf6158.png">
C'è un problema anche con i dati del Friuli-Venezia Giulia: sono scomparse tutte le vaccinazioni degli ospiti delle RSA, e anche quelle della categoria "over 80".

**Comment by accdavlo** [comment]
Problema simile per Valle d'Aosta e mi sembra anche in Lombardia. 
In valle d'aosta ci sono solo "categoria_personale_non_sanitario" e in Lombardia non ci sono ospiti_rsa che c'erano qualche giorno fa.
![Screenshot from 2021-01-19 23-46-30](https://user-images.githubusercontent.com/77506681/105103346-c4f3fb80-5ab0-11eb-8d6a-4ec9ebdbbbef.png)

**Comment by lvegro** [comment]
> 
> 
> Seguo, e aggiungo: si potrebbe avere un chiarimento sulla differenza tra "categoria_personale_non_sanitario" e "categoria_over_80"?
> Nel caso in cui la prima si riferisca, in senso generale, a tutto il resto della popolazione (non oss, e non ospite di rsa), ci sarebbe una sovrapposizione con "categoria_over_80" (per i dati in fascia_anagrafica = 80-89/90+).
> 
> Vi sarei grato se poteste chiarire.
> Grazie

ciao, per chiarimenti sul dominio della variabile (non esposta) "categoria" c'è la issue #26

**Comment by datateam-opendata** [comment]
Grazie @LorenzoRuff per la segnalazione. In questa settimana i dati sono in fase di consolidamento da parte delle Regioni e potrebbero subire alcune variazioni. Abbiamo provveduto a correggere l'anomalia segnalata.

In fase di vaccinazione viene espressa una categoria di appartenenza prevalente. Questo significa che, ad esempio, chi rientra nella categoria Over80 non rientra in altre categorie. Questo esclude sovrapposizioni di appartenenza.

Procediamo a chiudere la issue in quanto risolta. Grazie ancora a tutti.
