### ISSUE TITLE
Totale persone vaccinate

### ISSUE THREAD

**Issue by Conlaenne** [italia/covid19-opendata-vaccini#46]
Buongiorno, 
dall'aggiornamento a ieri (19/01/2021) alle ore 21:05 risultava un TOTALE PERSONE VACCINATE pari a 6881. Dall'aggiornamento odierno (20/01/2021) alle ore 11:04 risulta un TOTALE PERSONE VACCINE pari a 5864. Il suddetto dato risulta dunque in diminuzione (mentre da attesa dovrebbe risultare in aumento o, al più, ahimè, stabile). È possibile avere spiegazioni in merito?
Grazie mille e buona giornata.

**Comment by datateam-opendata** [comment]
Grazie @Conlaenne per l'importante segnalazione. Abbiamo avviato una serie di controlli sul dato al fine di identificare la causa dell'anomalia. Grazie ancora.

**Comment by datateam-opendata** [comment]
@Conlaenne i dati sono in fase di consolidamento e abbiamo provveduto a segnalare l'anomalia che è stata risolta. Grazie ancora per la issue. Provvediamo a chiuderla perché risolta.
