### ISSUE TITLE
Errore Moderna seconda dose 

### ISSUE THREAD

**Issue by devtechk** [italia/covid19-opendata-vaccini#47]
Salve, sto utilizzando questi opendata e mi sono accorto di un errore, o almeno penso che lo sia. 
Dato che il vaccino Moderna ha solo bisogno di una somministrazione ovvero una sola dose per persona, non capisco perché nel json somministrazione-vaccini-latest.json ritornate per l'index 3309 (area: "VEN")
come seconda dose somministrata il valore 1.

Non dovrebbe essere sempre a 0 dato che la seconda dose non è prevista?
`{index: 3309, data_somministrazione: "2021-01-18T00:00:00.000Z", fornitore: "Moderna", area: "VEN", fascia_anagrafica: "80-89", …}
area: "VEN"
categoria_operatori_sanitari_sociosanitari: 0
categoria_ospiti_rsa: 42
categoria_over80: 0
categoria_personale_non_sanitario: 3
data_somministrazione: "2021-01-18T00:00:00.000Z"
fascia_anagrafica: "80-89"
fornitore: "Moderna"
index: 3309
prima_dose: 44
seconda_dose: 1
sesso_femminile: 42
sesso_maschile: 3`
![image](https://user-images.githubusercontent.com/22073497/105335139-f87d7580-5bd7-11eb-821f-41bd0178a820.png)

**Comment by datateam-opendata** [comment]
Grazie @devtechk per la segnalazione.  I dati sono in fase di consolidamento e verificheremo con la Regione interessata. Grazie ancora.

**Comment by FrancescoBernardii** [comment]
Salve, se posso aggiungere i miei due cents: il vaccino moderna richiede due somministrazioni, come il vaccino di Pfizer/BionTech. 

> How is COVID-19 Vaccine Moderna used?
COVID-19 Vaccine Moderna is given as two injections, usually into the muscle of the upper arm, 28 days apart.


Fonte: https://www.ema.europa.eu/en/medicines/human/EPAR/covid-19-vaccine-moderna

**Comment by devtechk** [comment]
Grazie Francesco, allora i media riferiscono informazioni inesatte. Perché ho sempre saputo che sarebbe servita una sola dose. Ti ringrazio, ad ogni modo penso verificheranno.
