### ISSUE TITLE
I dati di Sicilia e Calabria sono fermi al 17 Gennaio

### ISSUE THREAD

**Issue by gust0o** [italia/covid19-opendata-vaccini#48]
Ho notato che i dati giornalieri di Sicilia e Calabria sono fermi al 17 Gennaio, è un problema del dataset?

**Comment by datateam-opendata** [comment]
Grazie @gust0o per la issue. A partire dal 18 gennaio i dati di tutte le Regioni sono in fase di consolidamento e i dati delle due Regioni saranno disponibili a breve. Provvediamo a chiudere questa issue perché in fase di risoluzione. Grazie ancora.
