### ISSUE TITLE
Info sigle regioni

### ISSUE THREAD

**Issue by chuck2098** [italia/covid19-opendata-vaccini#52]
Salve,
Sono stato l'unico che non è riuscito ad interpretare le seguenti sigle delle regioni: **PAT, PAB** ?

Grazie, Saluti

**Comment by chuck2098** [comment]
Ho appena risolto, grazie lo stesso !

**Comment by aborruso** [comment]
Avevo aperto [una issue](https://github.com/italia/covid19-opendata-vaccini/issues/1) a tema, perché l'utilizzo di sigle non standard e non documentate non è cosa buona.

Purtroppo è stata chiusa

**Comment by datateam-opendata** [comment]
Grazie @chuck2098 per la issue e, soprattutto, grazie @aborruso per i preziosi suggerimenti. Stiamo lavorando per estendere i codici geografici con una codifica standard (NUTS e ISTAT) che consentirà una gestione facilitata del dato geografico. Estenderemo la roadmap (vi anticipo che contiamo di applicare tale estensione già per il prossimo venerdì). Grazie ancora per i vostri preziosi consigli.
