### ISSUE TITLE
Provincia autonoma di BZ: Più dosi somministrate del totale ricevute

### ISSUE THREAD

**Issue by carmelolg** [italia/covid19-opendata-vaccini#60]
Nell'[aggiornamento di oggi](https://github.com/italia/covid19-opendata-vaccini/blob/master/dati/vaccini-summary-latest.csv), la percentuale di dosi somministrate per la PAB risulta di **100,5%**

Risultano più dosi somministrate della quantità ottenuta. 
Penso sia un errore a meno che non sono state _prestate_  dosi da altre regioni.

Grazie

**Comment by TheFe91** [comment]
Ciao! Penso che quando superano il 100% indicano che hanno estratto da una fiala 6 dosi e non 5. Loro calcolano il totale delle dosi sulla base del fatto che da una fiala si riescono ad estrarre 5 dosi, ma a volte se ne riescono a fare 6 (l'han detto in TV 10 giorni fa). Credo sia x questo che hanno superato il 100%.

Poo sul fatto che sia una complesso da leggere concordo con te.

**Comment by FrancescoBernardii** [comment]
cfr #23

**Comment by carmelolg** [comment]
chiudo poiché non più rilevante
