### ISSUE TITLE
DATI LOMBARDIA 2021-01-25

### ISSUE THREAD

**Issue by makk001** [italia/covid19-opendata-vaccini#61]
Non sono stati inseriti in data_somministrazione":"2021-01-25T00:00:00.000Z" i dati della Lombardia.

Quindi il conteggio dei area ITA è sbagliato  per data_somministrazione":"2021-01-25T00:00:00.000Z" ?

**Comment by datateam-opendata** [comment]
Grazie @makk001 per la issue. I dati in questo momento sono aggiornati correttamente. Provvediamo a chiudere la issue perché risolta. Grazie ancora.
