### ISSUE TITLE
distribuzione vaccini

### ISSUE THREAD

**Issue by LP160476** [italia/covid19-opendata-vaccini#63]
Ho saputo da alcuni sanitari che, se i soggetti prenotati non si presentano all'appuntamento, i vaccini non utilizzati sono spesso buttati.
Si tratta di uno spreco intollerabile che va prontamente risolto consentendo, come mi risulta accada in Israele, di usare i vaccini già scongelati e che non possono essere più conservati per immunizzare chiunque si presenti a fine giornata presso il centro di vaccinazione, senza avere riguardo dei criteri di priorità individuati dal Governo.

**Comment by datateam-opendata** [comment]
Ciao @LP160476 questa è una repository GitHub dedicata alla pubblicazione degli Open Data sulle vaccinazioni in Italia. Le issue aperte devono essere relative alla qualità del dato e al suo utilizzo. Provvediamo a chiudere la issue perché non rilevante. Grazie.
