### ISSUE TITLE
Index non corretti in summary-latest.json

### ISSUE THREAD

**Issue by faccioo** [italia/covid19-opendata-vaccini#64]
Gli index nel sommario delle regioni sono sbagliati, non sono più in ordine alfabetico. Ora index =0 corrisponde a FVG e non Abruzzo. Chiedo che vengano rimessi in ordine alfabetico, grazie.

**Comment by datateam-opendata** [comment]
Grazie @faccioo per la issue. Nelle prossime pubblicazioni l'indice tornerà corretto. Provvediamo a chiudere la issue perché sarà risolta dalla prossima pubblicazione. Grazie molte.
