### ISSUE TITLE
Seconda dose 

### ISSUE THREAD

**Issue by MarcoBrenna97** [italia/covid19-opendata-vaccini#68]
Serve una colonna "seconda dose" nella tabella, altrimenti si ha un report generale e non per singola regione. Non si comprende quante seconde dosi sono state somministrate nelle singole regioni.

**Comment by datateam-opendata** [comment]
Grazie @MarcoBrenna97 per la issue. Le seconde dosi sono presenti sui file già dal 18/01/2021 (è riportato anche nel file di Changelog.md). Chiudiamo la issue perché risolta. Grazie ancora.
