### ISSUE TITLE
Aggiungere le informazioni relative al tipo di vaccino somministrato/fornito

### ISSUE THREAD

**Issue by lvegro** [italia/covid19-opendata-vaccini#7]
Buonasera,
sarebbe utile avere a disposizione anche informazioni sul tipo/produttore dei vaccini somministrati e consegnati (p.es. Pfizer, Moderna, Astra Zeneca). Questa informazione sembra essere disponibile nei dati granulari esposti dalla dashboard -- PF/BT per Pfizer/Biotech ad esempio:

![immagine](https://user-images.githubusercontent.com/5043115/103672778-11055300-4f7d-11eb-806e-a007f59c3e08.png)

Grazie

**Comment by ludomaster** [comment]
Ciao @lvegro, posso chiederti dove hai trovato questi dati? Qual è l'endpoint?

**Comment by diabolicus23** [comment]
Le prime dosi di Moderna sono già state consegnate. Si possono avere indicazioni su se e quando il dato sul tipo di vaccino consegnato e somministrato verrà inserito?

**Comment by aborruso** [comment]
Nelle API della prima dashboard, sono apparsi le prime somministrazioni di Moderna https://api.gitrows.com/@github/ondata/covid19italia/webservices/vaccini/processing/datiRegioni/19.csv?vaccino=Moderna

**Comment by datateam-opendata** [comment]
Grazie @lvegro per la issue. Abbiamo provveduto a pubblicare il nome del fornitore sia per i dati relativi alle consegne che alle somministrazioni. Procediamo a chiudere la issue. Grazie ancora.
