### ISSUE TITLE
Errore dosi somministrate/dosi consegnate Campania

### ISSUE THREAD

**Issue by BHackFox** [italia/covid19-opendata-vaccini#76]
Salve volevo informarmi di una discordanza per i dati della Campania.
Dosi somministrate: 180203
Dosi consegnate: 179545
Rapporto: 100.37%
Per caso è dovuto a un errore nell'invio dei dati odierni della regione Campania?

**Comment by FrancescoBernardii** [comment]
Ciao, ti segnalo l'issue #23 dove si rispondeva a questa domanda.
