### ISSUE TITLE
somministrazioni-vaccini-latest.csv

### ISSUE THREAD

**Issue by Diego-85** [italia/covid19-opendata-vaccini#78]
Buonasera, qualcuno mi sa dire se il formato di questo file è cambiato ultimamente ? sembra ci sia un qualche tag errato nella struttura tale da non riconoscerlo come tabella.
Grazie

**Comment by aborruso** [comment]
Ciao @Diego-85 l'ho scaricato e non emergono errori.

Che errori riscontri? Come ci accedi?

**Comment by Diego-85** [comment]
Ciao Andrea e grazie. Il file di per se è corretto, io lo leggo in modalità
"web" con uno strumento di bi. Lo ho usato regolarmente fino alla settimana
scorsa, la differenza la noti anche visualizzandolo direttamente in github,
gli altri file csv si vedono come tabella, questo come file di testo.


Il Mer 3 Feb 2021, 16:42 Andrea Borruso <notifications@github.com> ha
scritto:

**Comment by aborruso** [comment]
Ciao @Diego-85 , occhio: prima della bi, alcuni elementi utili di base (non mi odiare).

Quello di cui parli non è un file CSV, ma una rappresentazione HTML. Quando il numero di righe diventano tante, github non ne fa più una preview pulita e ti avvisa

![image](https://user-images.githubusercontent.com/30607/106794128-ab2de900-6658-11eb-93f8-e1401d72206a.png)

L'URL di quel file CSV è questo <https://github.com/italia/covid19-opendata-vaccini/raw/master/dati/somministrazioni-vaccini-latest.csv> 

E lo ricavi al click su Raw

![image](https://user-images.githubusercontent.com/30607/106794243-d7496a00-6658-11eb-96bc-c006a85c0bd0.png)

**Comment by Diego-85** [comment]
Ottimo Andrea, sono nuovo di github e non conoscevo questa differenza. Con i link originale raw in effetti funziona bene.
Grazie mille per il tuo aiuto e scusa per la domanda scema ;)

**Comment by aborruso** [comment]
@Diego-85 non era scema e non ti devi scusare. Buon lavoro
