### ISSUE TITLE
File Update Stopped

### ISSUE THREAD

**Issue by antoniocaruso** [italia/covid19-opendata-vaccini#83]
Il dato delle consegne è aggiornato al 10, dopo il 10/02 non vi sono più riportate consegne.
Tutto questo mi sembra in contrasto con quanto viene comunicato sui quotidiani, in particolare
le consegne il recente lotto di Astrazeneca e di Moderna.

Mi sembra che ci sia qualche problema anche nella gestione delle somministrazioni di Astrazeneca.

**Comment by lorenzobini1** [comment]
Buongiorno, antoniocaruso. Premetto che sono un neofita assoluto su questa piattaforma e ho solo da imparare, ma anch'io ho il tuo problema. L'ho momentaneamente risolto rimuovendo e poi reinserirendo l'indirizzo github su visual code studio. Ma so già che questo problema si ripresenterà al prossimo aggiornamento dati perchè non ho ancora risolto l'autorefresh dei dati su github. Sto cercando un tutorial o un forum in grado di aiutarmi ma ancora non ho risolto perchè, ovviamente, non va assolutamente rimuovere e poi reinserire un repository github tutti i giorni e per più volte al giorno per ottenere i più recenti dati disponibili.

**Comment by antoniocaruso** [comment]
Non è un problema di Sync con il repository.
Parlo proprio dell'attendibilità del dato.
Rispetto a questo ad esempio

https://www.adnkronos.com/vaccino-covid-distribuite-a-regioni-quasi-425mila-dosi-astrazeneca-e-moderna_61Pefy9fNTqkzW8NyOgacT

Se queste dosi sono arrivate al momento il portale non le considera. Non so quale sia la catena che porta alla pubblicazione aggiornata qui su GitHub ma osservo delle discrepanze tra la comunicazione generale e la pratica (ho amici docenti vaccinati già in Toscana con Astrazeneca).

A me pare che il senso di questo repository non sia molto chiaro. Serve a monitorare centralmente le dosi consegnate ? (Servono update RealTime sulle consegne e somministrazioni) Serve a monitorare il progresso delle varie fasi di vaccinazione? (Serve maggior dettaglio sulle fasce, che man mano vedranno introdotte altre sottopopolazioni (docenti,forze armate) e la loro numerosità). 
Insomma se si devono pubblicare dati che siano di qualità o diventano numeri al lotto.

**Comment by camicius** [comment]
Il problema continua a presentarsi, anzi si aggrava. Non sono segnate consegne dopo il 13/02, ma è impossibile, visto che ci sono parecchie regioni già ieri sera con scorta negativa. Peraltro è incomprensibile come un dato che "matura" a livello centrale (posso contare le dosi che spedisco o che faccio consegnare) sia meno aggiornato di un dato che matura a livello periferico (la somministrazione delle dosi che avviene a Ponte di Legno o a Entraque deve essere comunicata a livello regionale e poi arrivare a livello centrale).

**Comment by datateam-opendata** [comment]
Grazie @antoniocaruso per la issue. Le consegne sono state aggiornate a seguito di consolidamento. Inoltre, @camicius le ultime consegne sono relative al 18 febbraio. Provvediamo a chiudere la issue perché risolta. Grazie ancora a tutti.

**Comment by camicius** [comment]
Adesso le consegne sono al 18 febbraio, ma quando ho commentato (era il 19) le consegne del 18 non erano ancora nel repository. Questo ovviamente manda in confusione ogni analisi basata sul "contare le scorte". E ripeto, capisco se la comunicazione della somministrazione di un vaccino fatto nella remota provincia italiana arrivi con 2-3 giorni di ritardo. Meno comprensibile che la comunicazione di una spedizione organizzata centralmente, venga contabilizzata con 3-5 giorni di ritardo (il 17 sono state aggiunte le consegne del 13, il 19 sono stati aggiunti quelli dal 15 al 18). 
La cosa si presenta abbastanza regolarmente dai primi di febbraio.
