### ISSUE TITLE
Inventario negativo

### ISSUE THREAD

**Issue by Rbbn1991** [italia/covid19-opendata-vaccini#86]
Salve, 

per curiosita' ho provato a calcolare la posizione dell' inventario giorno per giorno sommando le consegne (positive) ed il consumo (vaccinazioni fatte considerate negative come consumazioni) e facendo un running total ordinando i giorni. Quello che mi ha stupito e' che in certi casi si hanno valori negativi per esempio:

Campagna,
Bolzano
Marche.

Allego il data model trasformato usando i dati che postate.
[projected_inventory.xlsx](https://github.com/italia/covid19-opendata-vaccini/files/6012962/projected_inventory.xlsx)

**Comment by datateam-opendata** [comment]
Grazie @Rbbn1991 per la issue. Come già spiegato in passato, questo è dovuto all'utilizzo dell'extra dose da parte delle autorità competenti (es. sesta dose Pfizer). Provvediamo a chiudere la issue perché risolta. Grazie ancora.
