### ISSUE TITLE
Nuove categorie non ancora aggiunte

### ISSUE THREAD

**Issue by paolo-restuccia** [italia/covid19-opendata-vaccini#88]
Nel Changelog è stato riportato di recente che a partire dal 20 febbraio sarebbero apperse nei vari file le categorie **categoria_forze_armate** e **categoria_personale_scolastico**. Ma al momento queste categorie non compaiono da nessuna parte. C'è un motivo per questa discrepanza? Grazie in anticipo.

**Comment by datateam-opendata** [comment]
Grazie @paolo-restuccia per la issue. Le modifiche alla base dati saranno rilasciate nella giornata odierna. Provvediamo a chiudere la issue perché in risoluzione a breve. Grazie ancora.
