### ISSUE TITLE
Potremmo avere una versione del file Changelog compatibile con feed readers?

### ISSUE THREAD

**Issue by giasar** [italia/covid19-opendata-vaccini#91]
Ho necessità di seguire continuamente le modifiche del dataset poiché potrebbero creare problemi al mio programma che utilizza questi dati frequentemente. Il fatto che mi devo ricordare ogni tanto di controllare il file Changelog.md manualmente è troppo pericoloso.

Propongo di pubblicare un nuovo file nel repo leggibile da feed readers così chi è interessato può ricevere lì gli aggiornamenti. Per il formato proporrei, invece che Atom o RSS, il formato [JSON Feed](https://jsonfeed.org/version/1.1) siccome è molto più leggibile e facilmente aggiornabile dai mainteners ed è ormai compatibile con tutti i feed readers più diffusi (Feedly, Feedbin, NewsBur, Inoreader, Reeder e potrei continuare).

Vi faccio un esempio veloce parziale (con solo l'ultimo aggiornamento) di cosa sarebbe:
```
{
    "version": "https://jsonfeed.org/version/1.1",
    "title": "Changelog covid19-opendata-vaccini",
    "home_page_url": "https://github.com/italia/covid19-opendata-vaccini",
    "feed_url": "https://github.com/italia/covid19-opendata-vaccini/blob/master/Changelog.json",
    "items": [
        {
            "id": "5",
            "content_text": "25/02/2021. Sarà aggiunto il file contenente i principali punti di somministrazione suddivisi per tipologia (punti-somministrazione-tipologia). ll file punti-somministrazione-latest sarà dismesso nei prossimi giorni.",
            "url": "https://github.com/italia/covid19-opendata-vaccini/blob/master/Changelog.md",
            "date_published": "2021-02-25T18:29:00+01:00"
        }
    ]
}
```
Appunto ogni volta che c'è un nuovo aggiornamento si aggiunge un object all'array items con un id progressivo, il corpo dell'aggiornamento, come url lo stesso di volta in volta del file Changelog.md e la data di pubblicazione attuale (formato rfc 3339). In caso in cui viene modificato un aggiornamento successivamente, si inserisce anche un campo date_modified con la data di modifica.

Se i mainteners sono disposti appunto a mantenere un file così nel tempo, aggiungendo quindi i nuovi aggiornamenti sia a Changelod.md che a questo nuovo Changelog.json, io sono disposto a creare il nuovo file, con tutti i vecchi aggiornamenti già scritti, con una PR. So che è una cosa in più da gestire e magari non interessa a tutti, ma ecco credo che ci siano persone nella mia stessa situazione a cui farebbe davvero la differenza tra rompere e non rompere un programma.

**Comment by aborruso** [comment]
Ciao @giasar ad ogni risorsa in github è associato un output compatibile con un feed reader.

Per il file `Changelog.md` è

<https://github.com/italia/covid19-opendata-vaccini/commits/master/Changelog.md.atom>

Non è nel formato che hai proposto, ma è compatibile con tutti i lettori RSS e ti avviserebbe quindi al cambiamento. Ma magari non ho capito la tua richiesta.

**Comment by giasar** [comment]
Grazie della risposta @aborruso. Sì ne ero a conoscenza, tuttavia pensavo che una modifica al file Changelog non sempre equivalesse con un nuovo aggiornamento (magari viene modificato la formattazione oppure corretti degli errori oppure altre modifiche che non necessariamente aggiungono semplicemente un nuovo aggiornamento).  Ma mi hai fatto riflettere sul fatto che è di gran lungo più semplice che filtro io queste eccezioni quando ricevo degli aggiornamenti, che se i mainteners devono gestire un nuovo file e ricordarsi di aggiornarlo. Chiudo.
